# apigen configuration file.
# Strings should use single quotes

[Models]

Pkgs = [
  'github.com/abiiranathan/apigen/models',
  'github.com/abiiranathan/apigen/views',
]

Skip = []
ReadOnly = ['github.com/abiiranathan/apigen/views']

[Output]
OutDir = '.'
ServiceName = 'services'

[overrides]
[overrides.types]
Sex = '"Male" | "Female"'

[overrides.fields]
gender = 'Sex'
