# apigen configuration file.
# Strings should use single quotes

RootPkg='github.com/abiiranathan/apigen'

[Models]
Pkg='github.com/abiiranathan/apigen/models'
Skip=[]

[Output]
OutDir='.'
ServiceName='services'
HandlersName='handlers'
