// Package rawgen generates raw PostgreSQL Go code for a given model struct.
// It produces functions that use database/sql directly (no ORM) for
// Insert, QueryOne, Query, Delete, and Update operations.
package rawgen

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/abiiranathan/apigen/parser"
	"github.com/iancoleman/strcase"
)

// Options controls what code is generated.
type Options struct {
	// ModelName is the struct name to generate for (e.g. "User").
	ModelName string

	// ModelPkg is the import path of the models package (e.g. "github.com/user/app/models").
	ModelPkg string

	// SelectFields limits the SELECT columns. Empty means all non-relation columns.
	SelectFields []string

	// OmitFields excludes specific columns from all generated queries.
	OmitFields []string

	// Filters are custom WHERE clauses appended to Query/QueryOne (e.g. "age > $N", "name ILIKE $N").
	// Each filter becomes a function parameter. Use $N as a placeholder — it will be
	// replaced with the correct positional parameter number.
	Filters []Filter

	// TableName overrides the default snake_case plural table name.
	TableName string
}

// Filter represents a custom WHERE clause added to Query functions.
type Filter struct {
	// Column is the Go field name (will be snake_cased for SQL).
	Column string
	// Op is the SQL operator (e.g. "=", ">", "ILIKE", "IN").
	Op string
	// GoType is the Go type for the function parameter (e.g. "string", "int").
	GoType string
	// Nullable when true wraps the filter in an if-check so it's only applied when non-zero.
	Nullable bool
}

// column holds resolved column metadata for code generation.
type column struct {
	GoName   string // e.g. "Name"
	ColName  string // e.g. "name"
	GoType   string // e.g. "string"
	IsFK     bool   // foreign key / relation field — excluded from raw queries
	IsPK     bool
	BaseType string
}

// Generate writes raw PostgreSQL Go code to w for the specified model.
func Generate(w io.Writer, meta []parser.StructMeta, opts Options) error {
	// Find the target struct
	var target *parser.StructMeta
	for i := range meta {
		if meta[i].Name == opts.ModelName {
			target = &meta[i]
			break
		}
	}
	if target == nil {
		return fmt.Errorf("model %q not found in parsed structs", opts.ModelName)
	}

	tableName := opts.TableName
	if tableName == "" {
		tableName = strcase.ToSnake(opts.ModelName) + "s"
	}

	cols := resolveColumns(target, opts)

	pkgName := "models"
	if parts := strings.Split(opts.ModelPkg, "/"); len(parts) > 0 {
		pkgName = parts[len(parts)-1]
	}

	ident := strings.ToLower(opts.ModelName[:1]) // single-letter receiver/var

	data := templateData{
		ModelName:    opts.ModelName,
		ModelPkg:     opts.ModelPkg,
		ModelPkgName: pkgName,
		TableName:    tableName,
		Ident:        ident,
		Columns:      cols,
		PKCol:        findPK(cols),
		Filters:      opts.Filters,
	}

	return writeCode(w, data)
}

func resolveColumns(st *parser.StructMeta, opts Options) []column {
	cols := make([]column, 0, len(st.Fields))
	for _, f := range st.Fields {
		if f.Preload {
			continue // skip relation fields
		}

		colName := strcase.ToSnake(f.Name)

		if len(opts.SelectFields) > 0 && !slices.Contains(opts.SelectFields, f.Name) {
			continue
		}
		if slices.Contains(opts.OmitFields, f.Name) {
			continue
		}

		cols = append(cols, column{
			GoName:   f.Name,
			ColName:  colName,
			GoType:   f.Type,
			IsFK:     f.Preload,
			IsPK:     f.Name == "ID",
			BaseType: f.BaseType,
		})
	}
	return cols
}

func findPK(cols []column) *column {
	for i := range cols {
		if cols[i].IsPK {
			return &cols[i]
		}
	}
	return nil
}

type templateData struct {
	ModelName    string
	ModelPkg     string
	ModelPkgName string
	TableName    string
	Ident        string
	Columns      []column
	PKCol        *column
	Filters      []Filter
}

func writeCode(w io.Writer, d templateData) error {
	p := func(format string, args ...any) {
		fmt.Fprintf(w, format, args...)
	}

	// Header
	p("// Code generated by apigen rawgen; DO NOT EDIT.\n")
	p("package queries\n\n")
	p("import (\n")
	p("\t\"context\"\n")
	p("\t\"database/sql\"\n")
	p("\t\"fmt\"\n")
	if len(d.Filters) > 0 {
		p("\t\"strings\"\n")
	}
	p("\n")
	p("\t%q\n", d.ModelPkg)
	p(")\n\n")

	writeInsert(w, d)
	if d.PKCol != nil {
		writeQueryOne(w, d)
		writeDelete(w, d)
		writeUpdate(w, d)
	}
	writeQuery(w, d)

	return nil
}

// --- INSERT ---
func writeInsert(w io.Writer, d templateData) {
	p := func(format string, args ...any) { fmt.Fprintf(w, format, args...) }

	// Columns to insert (exclude PK if autoIncrement)
	insertCols := nonPKCols(d.Columns)

	colNames := make([]string, len(insertCols))
	placeholders := make([]string, len(insertCols))
	scanArgs := make([]string, len(insertCols))
	for i, c := range insertCols {
		colNames[i] = c.ColName
		placeholders[i] = fmt.Sprintf("$%d", i+1)
		scanArgs[i] = fmt.Sprintf("%s.%s.%s", d.Ident, d.ModelPkgName, c.GoName)
	}

	p("// Insert%s inserts a new %s and returns the generated ID.\n", d.ModelName, d.ModelName)
	p("func Insert%s(ctx context.Context, db *sql.DB, %s *%s.%s) error {\n",
		d.ModelName, d.Ident, d.ModelPkgName, d.ModelName)
	p("\tconst query = `INSERT INTO %s (%s) VALUES (%s)", d.TableName,
		strings.Join(colNames, ", "), strings.Join(placeholders, ", "))
	if d.PKCol != nil {
		p(" RETURNING %s", d.PKCol.ColName)
	}
	p("`\n")

	// Build args
	args := make([]string, len(insertCols))
	for i, c := range insertCols {
		args[i] = fmt.Sprintf("%s.%s", d.Ident, c.GoName)
	}

	if d.PKCol != nil {
		p("\treturn db.QueryRowContext(ctx, query,\n")
		for i, a := range args {
			if i < len(args)-1 {
				p("\t\t%s,\n", a)
			} else {
				p("\t\t%s,\n", a)
			}
		}
		p("\t).Scan(&%s.%s)\n", d.Ident, d.PKCol.GoName)
	} else {
		p("\t_, err := db.ExecContext(ctx, query,\n")
		for _, a := range args {
			p("\t\t%s,\n", a)
		}
		p("\t)\n")
		p("\treturn err\n")
	}
	p("}\n\n")
}

// --- QUERY ONE ---
func writeQueryOne(w io.Writer, d templateData) {
	p := func(format string, args ...any) { fmt.Fprintf(w, format, args...) }

	colList := columnList(d.Columns)
	scanFields := scanFieldList(d.Columns, d.Ident)

	p("// Get%s retrieves a single %s by primary key.\n", d.ModelName, d.ModelName)
	p("func Get%s(ctx context.Context, db *sql.DB, id %s) (*%s.%s, error) {\n",
		d.ModelName, d.PKCol.GoType, d.ModelPkgName, d.ModelName)
	p("\tconst query = `SELECT %s FROM %s WHERE %s = $1`\n",
		colList, d.TableName, d.PKCol.ColName)
	p("\tvar %s %s.%s\n", d.Ident, d.ModelPkgName, d.ModelName)
	p("\terr := db.QueryRowContext(ctx, query, id).Scan(\n")
	p("\t\t%s,\n", scanFields)
	p("\t)\n")
	p("\tif err != nil {\n")
	p("\t\treturn nil, err\n")
	p("\t}\n")
	p("\treturn &%s, nil\n", d.Ident)
	p("}\n\n")
}

// --- QUERY (List) ---
func writeQuery(w io.Writer, d templateData) {
	p := func(format string, args ...any) { fmt.Fprintf(w, format, args...) }

	colList := columnList(d.Columns)
	scanFields := scanFieldList(d.Columns, d.Ident)

	// Build function signature with filter params
	var params strings.Builder
	params.WriteString("ctx context.Context, db *sql.DB")
	if len(d.Filters) > 0 {
		for _, f := range d.Filters {
			paramName := strcase.ToLowerCamel(f.Column)
			if f.Nullable {
				fmt.Fprintf(&params, ", %s *%s", paramName, f.GoType)
			} else {
				fmt.Fprintf(&params, ", %s %s", paramName, f.GoType)
			}
		}
	}

	p("// Query%ss retrieves %s records matching the provided filters.\n", d.ModelName, d.ModelName)
	p("func Query%ss(%s) ([]*%s.%s, error) {\n", d.ModelName, params.String(), d.ModelPkgName, d.ModelName)
	p("\tbaseQuery := `SELECT %s FROM %s`\n", colList, d.TableName)

	if len(d.Filters) > 0 {
		p("\n\tconditions := make([]string, 0, %d)\n", len(d.Filters))
		p("\targs := make([]any, 0, %d)\n", len(d.Filters))
		p("\tparamIdx := 1\n\n")

		for _, f := range d.Filters {
			paramName := strcase.ToLowerCamel(f.Column)
			colName := strcase.ToSnake(f.Column)
			if f.Nullable {
				p("\tif %s != nil {\n", paramName)
				p("\t\tconditions = append(conditions, fmt.Sprintf(\"%s %s $%%d\", paramIdx))\n", colName, f.Op)
				p("\t\targs = append(args, *%s)\n", paramName)
				p("\t\tparamIdx++\n")
				p("\t}\n")
			} else {
				p("\tconditions = append(conditions, fmt.Sprintf(\"%s %s $%%d\", paramIdx))\n", colName, f.Op)
				p("\targs = append(args, %s)\n", paramName)
				p("\tparamIdx++\n\n")
			}
		}

		p("\tif len(conditions) > 0 {\n")
		p("\t\tbaseQuery += \" WHERE \" + strings.Join(conditions, \" AND \")\n")
		p("\t}\n\n")
		p("\trows, err := db.QueryContext(ctx, baseQuery, args...)\n")
	} else {
		p("\trows, err := db.QueryContext(ctx, baseQuery)\n")
	}

	p("\tif err != nil {\n")
	p("\t\treturn nil, err\n")
	p("\t}\n")
	p("\tdefer rows.Close()\n\n")
	p("\tvar results []*%s.%s\n", d.ModelPkgName, d.ModelName)
	p("\tfor rows.Next() {\n")
	p("\t\tvar %s %s.%s\n", d.Ident, d.ModelPkgName, d.ModelName)
	p("\t\tif err := rows.Scan(\n")
	p("\t\t\t%s,\n", scanFields)
	p("\t\t); err != nil {\n")
	p("\t\t\treturn nil, err\n")
	p("\t\t}\n")
	p("\t\tresults = append(results, &%s)\n", d.Ident)
	p("\t}\n")
	p("\treturn results, rows.Err()\n")
	p("}\n\n")
}

// --- DELETE ---
func writeDelete(w io.Writer, d templateData) {
	p := func(format string, args ...any) { fmt.Fprintf(w, format, args...) }

	p("// Delete%s deletes a %s by primary key.\n", d.ModelName, d.ModelName)
	p("func Delete%s(ctx context.Context, db *sql.DB, id %s) error {\n",
		d.ModelName, d.PKCol.GoType)
	p("\tconst query = `DELETE FROM %s WHERE %s = $1`\n", d.TableName, d.PKCol.ColName)
	p("\tresult, err := db.ExecContext(ctx, query, id)\n")
	p("\tif err != nil {\n")
	p("\t\treturn err\n")
	p("\t}\n")
	p("\trows, err := result.RowsAffected()\n")
	p("\tif err != nil {\n")
	p("\t\treturn err\n")
	p("\t}\n")
	p("\tif rows == 0 {\n")
	p("\t\treturn sql.ErrNoRows\n")
	p("\t}\n")
	p("\treturn nil\n")
	p("}\n\n")
}

// --- UPDATE ---
func writeUpdate(w io.Writer, d templateData) {
	p := func(format string, args ...any) { fmt.Fprintf(w, format, args...) }

	updateCols := nonPKCols(d.Columns)
	setClauses := make([]string, len(updateCols))
	for i, c := range updateCols {
		setClauses[i] = fmt.Sprintf("%s = $%d", c.ColName, i+1)
	}
	pkParam := fmt.Sprintf("$%d", len(updateCols)+1)

	p("// Update%s updates all columns of a %s by primary key.\n", d.ModelName, d.ModelName)
	p("func Update%s(ctx context.Context, db *sql.DB, %s *%s.%s) error {\n",
		d.ModelName, d.Ident, d.ModelPkgName, d.ModelName)
	p("\tconst query = `UPDATE %s SET %s WHERE %s = %s`\n",
		d.TableName, strings.Join(setClauses, ", "), d.PKCol.ColName, pkParam)
	p("\tresult, err := db.ExecContext(ctx, query,\n")
	for _, c := range updateCols {
		p("\t\t%s.%s,\n", d.Ident, c.GoName)
	}
	p("\t\t%s.%s,\n", d.Ident, d.PKCol.GoName)
	p("\t)\n")
	p("\tif err != nil {\n")
	p("\t\treturn err\n")
	p("\t}\n")
	p("\trows, err := result.RowsAffected()\n")
	p("\tif err != nil {\n")
	p("\t\treturn err\n")
	p("\t}\n")
	p("\tif rows == 0 {\n")
	p("\t\treturn sql.ErrNoRows\n")
	p("\t}\n")
	p("\treturn nil\n")
	p("}\n\n")
}

// --- helpers ---

func nonPKCols(cols []column) []column {
	out := make([]column, 0, len(cols))
	for _, c := range cols {
		if !c.IsPK {
			out = append(out, c)
		}
	}
	return out
}

func columnList(cols []column) string {
	names := make([]string, len(cols))
	for i, c := range cols {
		names[i] = c.ColName
	}
	return strings.Join(names, ", ")
}

func scanFieldList(cols []column, ident string) string {
	fields := make([]string, len(cols))
	for i, c := range cols {
		fields[i] = fmt.Sprintf("&%s.%s", ident, c.GoName)
	}
	return strings.Join(fields, ", ")
}
