// Code generated by "apigen"; DO NOT EDIT.
package models

import (
	"database/sql/driver"
	"fmt"
)

var validValues = []string{
	"Male",
	"Female",
}

func (e Sex) IsValid() bool {
	for _, val := range validValues {
		if val == string(e) {
			return true
		}
	}
	return false
}

func (e Sex) ValidValues() []string {
	return validValues
}

func (e *Sex) Scan(src interface{}) error {
	source, ok := src.(string)
	if !ok {
		return fmt.Errorf("invalid value for %s: %s", "Sex", source)
	}
	*e = Sex(source)
	return nil
}

func (e Sex) Value() (driver.Value, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid value for %s", "Sex")
	}
	return string(e), nil
}

func (e Sex) DatabaseType() string {
	return "sex"
}

func (e Sex) GormDataType() string {
	return "sex"
}
